users/urls.py
from django.urls import path
from .views import ProfileDetailView, ProfileStudentCourseUpdate
from .views import profile , profile_detail
from .views import message


urlpatterns = [
   
    path('message/<str:slug>/', message, name = 'message'),
    path('', profile, name='profile-edit'),
    path('add/', ProfileStudentCourseUpdate.as_view(), name='profile-edit-courses'),
    path('<str:slug>/', profile_detail, name='profile-detail'),
    #path('<str:slug>/', ProfileDetailView.as_view(), name='profile-detail'),
]

groups/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from users.models import Profile
from social_app.models import StudentCourse
# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(StudentCourse, default='', on_delete=models.CASCADE, null=True)
    members = models.ManyToManyField(Profile)
    private = models.BooleanField(default=False)
    meeting_url = models.URLField(default='https://meet.google.com/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('group-detail', kwargs={'pk': self.pk})

social_app/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from users.models import Profile

# Create your models here.
class Course(models.Model):
    subject = models.CharField(max_length=4)
    catalog_number = models.CharField(max_length=4)
    class_title = models.CharField(max_length=100)

class StudentCourse(models.Model):
    # course = models.OneToOneField(Course, on_delete = models.CASCADE)
    subject = models.CharField(max_length=4, blank=True, verbose_name="Subject (ex. CS)")
    catalog_number = models.CharField(max_length=4, blank=True, verbose_name="Catalog Number (ex. 2150)")
    difficulty = models.SmallIntegerField(
        validators=[MaxValueValidator(10), MinValueValidator(1)], verbose_name="Difficulty from 1 (easy) to 10 (hard)")
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)


    def __str__(self):
        return self.subject + " " + self.catalog_number

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):

    YEAR_IN_SCHOOL_CHOICES = [
        ('1st', 'First-Year'),
        ('2nd', 'Second-Year'),
        ('3rd', 'Third-Year'),
        ('4th', 'Fourth-Year'),
        ('Other', 'Other'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    major = models.CharField(max_length=50, blank = True)
    year_in_school = models.CharField(
        max_length=5,
        choices=YEAR_IN_SCHOOL_CHOICES,
        blank = True,
    )
    bio = models.TextField(max_length=150, blank = True)

    def __str__(self):
        return f'{self.user.username} Profile'

    

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from groups.models import Group
from django.forms.models import inlineformset_factory
from social_app.models import StudentCourse, Course


class Message(forms.Form):
    #Email = User.email
    Subject = forms.CharField()
    emailContent = forms.CharField(label = "Message", widget = forms.Textarea(attrs = {'rows': 4, 'cols': 40}))
    def __str__(self):
        return self.Email


class AddToGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].queryset = Group.objects.filter(owner=self.user)

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model=User
        fields = ['username', 'first_name', 'last_name']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields = ['major', 'year_in_school','bio']
        labels = {
        'major': 'Major',
        'year_in_school': 'Year in School',
        'bio': 'Profile Bio',
        }

class StudentCourseForm(forms.ModelForm):

    class Meta:
        model = StudentCourse
        exclude = ()

    def clean_subject(self):
        return self.cleaned_data['subject'].upper()
    
    def clean(self):
        super(StudentCourseForm, self).clean()
        subject = self.cleaned_data.get('subject').upper()
        catalog_number = self.cleaned_data.get('catalog_number')
        if not (subject, catalog_number) in Course.objects.all().values_list('subject', 'catalog_number'):
            self._errors['subject'] = self.error_class([ 
                'Invalid Course'])
        return self.cleaned_data

StudentCourseFormSet = inlineformset_factory(
    Profile, StudentCourse, form=StudentCourseForm, extra=1, can_delete=True
    )

users/views.py
from django.shortcuts import render, redirect , get_object_or_404
from django.db import transaction
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView
from .forms import UserUpdateForm, ProfileUpdateForm, StudentCourseFormSet
from django.contrib import messages
from django.views.generic import DetailView
from .models import Profile
from groups.models import Group

from django.http import HttpResponseRedirect

from django.contrib.auth.models import User
from mysite.settings import EMAIL_HOST_USER
from . import forms
from django.core.mail import send_mail

from django.core.mail import EmailMessage
from django.views.generic.edit import FormMixin 


# Create your views here.

#DataFlair #Send Email
def message(request, slug):
    model = Profile
    sub = forms.Message()
    if request.method == 'POST':
        sub = forms.Message(request.POST)
        subject = str(sub['Subject'].value())
        message = str(sub['emailContent'].value())
        recepient = User.objects.get(username=slug).first_name
        email = EmailMessage(
            subject,
            message,
            #EMAIL_HOST_USER,
            request.user.first_name + ' has sent you a message from study connect <studybuddyuva@gmail.com>',
            [User.objects.get(username=slug).email],
            reply_to=[request.user.email],
            headers={'Message-ID': 'foo'},
            )
        email.send()
        return render(request, 'users/success.html', {'recepient': recepient})
    return render(request, 'users/message_form.html', {'form':sub})

def login(request):
    return render(request, 'users/login.html')

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, instance=request.user.profile) # add request.FILES as second parameter if using profile image
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
        messages.success(request, f'Your account has been updated!')
        return redirect('profile-edit') # start GET request
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)


    context = {
        'user_form': u_form,
        'profile_form' : p_form
    }

    return render(request, 'users/profile.html', context)

def profile_detail(request, slug, template_name='users/profile_detail.html'):
    profile= get_object_or_404(Profile, user__username=slug)

    if request.GET.get('group'):
        group_id = request.GET.get('group')
        Group.objects.get(id=group_id).members.add(profile)
        context_dict = {'object': request.user.profile}
        success_url = reverse_lazy('group-home')
        return HttpResponseRedirect(success_url)

    context_dict = {'object': profile}
    return render(request, "users/profile_detail.html", context_dict)

class ProfileDetailView(DetailView):
    model = Profile

    def get_slug_field(self):
        return 'user__username'
    
class ProfileStudentCourseUpdate(UpdateView):
    model = Profile
    fields = []
    success_url = reverse_lazy('profile-edit-courses')
    
    def get_object(self):
        return self.model.objects.get(pk=self.request.user.profile.pk)
    
    def get_context_data(self, **kwargs):
        data = super(ProfileStudentCourseUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['studentcourses'] = StudentCourseFormSet(self.request.POST, instance=self.object)
        else:
            data['studentcourses'] = StudentCourseFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        studentcourses = context['studentcourses']
        with transaction.atomic():
            self.object = form.save()

            if studentcourses.is_valid():
                studentcourses.instance = self.object
                studentcourses.save()
        return super(ProfileStudentCourseUpdate, self).form_valid(form)

users/templates/users/login.html
{% extends 'social_app/login_base.html'%}
{% load socialaccount %}
{% block main %}
<div class="container">
    <div class="d-flex align-items-center flex-column  justify-content-center login">
        <header>Study Connect </header>
        <header class=" mt-5">📓✏️</header>
        <a class="btn btn-success submit-button mt-5" href="{% provider_login_url 'google' %}">Login with Google</a>
        <h4 class="mt-5">Find your next study group.</h4>
        <h6 class="mt-5">Created by TheStudyBuddies</h6>
    </div>
</div>
{% endblock main %}

users/templates/users/message_form.html
{% extends 'social_app/base.html'%}
{% load static %}
{% load crispy_forms_tags %}


<head>
    {%block header%}
         <title>Message</title>
    {% endblock %}
      <!--   <link rel="stylesheet"                 href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">  -->
</head>
{% block content %}
<body>
    <center>
        <h1 class = 'alert alert-success'>Message</h1>
    </h3>
    <form method="POST">
        <!-- Very Important csrf Token -->
        {% csrf_token %}
        <div class = "form-group">
            <p>
            <h3>{{ form.as_p }}</h3>
        </p>
            <br>
            <input type="submit" name="message" class = 'btn btn-primary btn-lg'>
                </div>
            </form>
        </center>
</body>
{% endblock content %}

users/templates/users/profile.html
{% extends 'social_app/base.html'%}
{% load crispy_forms_tags %}

{%block header%}
Edit Your Profile 📋
{% endblock %}

{% block content %}
<div class="content-section">
    <div class="media">
        <!--<img class="rounded-circle account-img" src="{{ user.profile.image.url }}">-->
        <div class="media-body">
            <h2 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
    <!-- FORM HERE -->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ user_form | crispy }}
            {{ profile_form | crispy }}
        </fieldset>
        <div class="form-group">
            <a class="btn btn-info" href="{% url 'profile-edit-courses' %}">
                Edit Courses
            </a>
            <button class="btn btn-success" type="submit">
                Update
            </button>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/profile_detail.html
{% extends 'social_app/base.html'%}
{% block content %}
<div class="content-section">
    <div class="row">
        <div class="col-md-6 m-auto">
            <div><b>{{ object.user.first_name }} {{ object.user.last_name }}</b></div>
            <div> <b>Major:</b> {{ object.major }}</div>
            <div><b>Courses:</b>
                {% for StudentCourse in object.studentcourse_set.all %}
                {% if StudentCourse == object.studentcourse_set.last%}
                {{ StudentCourse.subject}} {{ StudentCourse.catalog_number}}
                {% else %}
                {{ StudentCourse.subject}} {{ StudentCourse.catalog_number}},
                {% endif %}
                {% endfor %}
            </div>
            <p><b>Bio:</b> {{object.bio}}</p>
            {% if object.user != user%}
            <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url  'message' object.user.username  %}">Message
                {{ object.user.first_name }}</a>

            <form action="" method="get">
                <label for="group">Add to {{ object.user.first_name }} Group</label>
                <select name="group">
                    <option value="">-----------------</option>
                    {%for group in user.profile.group_set.all %}
                    <option value="{{group.id}}">{{ group.name}}</option>
                    {% endfor %}
                    <input class="btn btn-sm btn-success ml-2" type="submit" />
            </form>
            {% endif %}


        </div>
        {% if object.user == user%}
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'profile-edit' %}">Edit Profile</a>
        </div>
        {% endif %}
    </div>

</div>
{% endblock content %}

users/templates/users/profile_form.html
{% extends 'social_app/base.html'%}
{% load static %}
{% load crispy_forms_tags %}

{%block header%}
Edit Your Profile 📋
{% endblock %}
{% block content %}
<h2>Edit Courses</h2>
<div class="col-md-12">
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}

        <table class="table">
            {{ studentcourses.management_form }}

            {% for form in studentcourses.forms %}
            {% if forloop.first %}
            <thead>
                <tr>
                    {% for field in form.visible_fields %}
                    <th>{{ field.label|capfirst }}</th>
                    {% endfor %}
                </tr>
            </thead>
            {% endif %}
            <tr class="{% cycle row1 row2 %} formset_row">
                {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
                    {% endif %}
                    {{ field.errors.as_p }}
                    {{ field }}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
        <a class="btn btn-secondary mr-5" href="{% url 'profile-edit' %}">Back to Profile</a>

        <input class="btn btn-success" type="submit" value="Save" />
    </form>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<!-- <script src="{% static 'formset/jquery.formset.js' %}"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"></script>
<script type="text/javascript">
    $('.formset_row').formset({
        addText: 'Add Course',
        deleteText: 'Remove',
        prefix: 'studentcourse_set'
    });
</script>
{% endblock content %}

users/templates/users/success.html
{% extends 'social_app/base.html'%}
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>

<head>
    <title>Success</title>
</head>

<body>
    {% block content %}

    <center>
        <h1>Email sent successfully to {{ recepient }}</h1>
        <a href="{% url 'profile-edit' %}"><button type="button" class="btn btn-primary">Back to Home</button></a>
    </center>
</body>
{% endblock content %}

</html>